services:
  - type: web
    name: gan-dganit
    runtime: static
    staticPublishPath: ./public
    buildCommand: echo "No build needed"
    headers:
      - path: /*
        name: Content-Type
        value: text/html; charset=utf-8
